name: weather
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # HTTP Client
  dio: ^5.4.0

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Location Services
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Network Connectivity
  connectivity_plus: ^5.0.2

  # Environment Variables
  flutter_dotenv: ^5.1.0

  # Performance & Caching
  cached_network_image: ^3.3.0

  # UI Enhancements
  cupertino_icons: ^1.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
  
